package com.fasepi.android.appet.usuario.Appet;

public enum EstadosUnidad {
	NUEVO_SERVICIO, BUSCANDO_APP, MOVIL_ASIGNADO, SERVICIO_EXITOSO, SERVICIO_CANCELADO_POR_TAXISTA, NO_HAY_MOVIL, USUARIO_A_BORDO, LLEGADA_DESTINO;
}
